services:
  - type: web
    name: malikina-api
    runtime: node
    plan: free
    buildCommand: cd api && npm install --legacy-peer-deps && npm run build
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
    branch: main
